// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: profile.proto

package org.fermat.redtooth.profiles_manager;

public final class ProfileOuterClass {
  private ProfileOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ProfileInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.fermat.redtooth.profiles_manager.ProfileInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bytes version = 1;</code>
     */
    com.google.protobuf.ByteString getVersion();

    /**
     * <code>string name = 2;</code>
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string type = 3;</code>
     */
    String getType();
    /**
     * <code>string type = 3;</code>
     */
    com.google.protobuf.ByteString
        getTypeBytes();

    /**
     * <code>string extraData = 4;</code>
     */
    String getExtraData();
    /**
     * <code>string extraData = 4;</code>
     */
    com.google.protobuf.ByteString
        getExtraDataBytes();

    /**
     * <code>bytes pubKey = 6;</code>
     */
    com.google.protobuf.ByteString getPubKey();

    /**
     * <code>string homeHost = 7;</code>
     */
    String getHomeHost();
    /**
     * <code>string homeHost = 7;</code>
     */
    com.google.protobuf.ByteString
        getHomeHostBytes();

    /**
     * <code>bytes img = 8;</code>
     */
    com.google.protobuf.ByteString getImg();
  }
  /**
   * Protobuf type {@code org.fermat.redtooth.profiles_manager.ProfileInfo}
   */
  public  static final class ProfileInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.fermat.redtooth.profiles_manager.ProfileInfo)
      ProfileInfoOrBuilder {
    // Use ProfileInfo.newBuilder() to construct.
    private ProfileInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ProfileInfo() {
      version_ = com.google.protobuf.ByteString.EMPTY;
      name_ = "";
      type_ = "";
      extraData_ = "";
      pubKey_ = com.google.protobuf.ByteString.EMPTY;
      homeHost_ = "";
      img_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private ProfileInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              version_ = input.readBytes();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 26: {
              String s = input.readStringRequireUtf8();

              type_ = s;
              break;
            }
            case 34: {
              String s = input.readStringRequireUtf8();

              extraData_ = s;
              break;
            }
            case 50: {

              pubKey_ = input.readBytes();
              break;
            }
            case 58: {
              String s = input.readStringRequireUtf8();

              homeHost_ = s;
              break;
            }
            case 66: {

              img_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ProfileInfo.class, Builder.class);
    }

    public static final int VERSION_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString version_;
    /**
     * <code>bytes version = 1;</code>
     */
    public com.google.protobuf.ByteString getVersion() {
      return version_;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private volatile Object name_;
    /**
     * <code>string name = 2;</code>
     */
    public String getName() {
      Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TYPE_FIELD_NUMBER = 3;
    private volatile Object type_;
    /**
     * <code>string type = 3;</code>
     */
    public String getType() {
      Object ref = type_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        type_ = s;
        return s;
      }
    }
    /**
     * <code>string type = 3;</code>
     */
    public com.google.protobuf.ByteString
        getTypeBytes() {
      Object ref = type_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        type_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EXTRADATA_FIELD_NUMBER = 4;
    private volatile Object extraData_;
    /**
     * <code>string extraData = 4;</code>
     */
    public String getExtraData() {
      Object ref = extraData_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        extraData_ = s;
        return s;
      }
    }
    /**
     * <code>string extraData = 4;</code>
     */
    public com.google.protobuf.ByteString
        getExtraDataBytes() {
      Object ref = extraData_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        extraData_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUBKEY_FIELD_NUMBER = 6;
    private com.google.protobuf.ByteString pubKey_;
    /**
     * <code>bytes pubKey = 6;</code>
     */
    public com.google.protobuf.ByteString getPubKey() {
      return pubKey_;
    }

    public static final int HOMEHOST_FIELD_NUMBER = 7;
    private volatile Object homeHost_;
    /**
     * <code>string homeHost = 7;</code>
     */
    public String getHomeHost() {
      Object ref = homeHost_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        homeHost_ = s;
        return s;
      }
    }
    /**
     * <code>string homeHost = 7;</code>
     */
    public com.google.protobuf.ByteString
        getHomeHostBytes() {
      Object ref = homeHost_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        homeHost_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IMG_FIELD_NUMBER = 8;
    private com.google.protobuf.ByteString img_;
    /**
     * <code>bytes img = 8;</code>
     */
    public com.google.protobuf.ByteString getImg() {
      return img_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!version_.isEmpty()) {
        output.writeBytes(1, version_);
      }
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, name_);
      }
      if (!getTypeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, type_);
      }
      if (!getExtraDataBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, extraData_);
      }
      if (!pubKey_.isEmpty()) {
        output.writeBytes(6, pubKey_);
      }
      if (!getHomeHostBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 7, homeHost_);
      }
      if (!img_.isEmpty()) {
        output.writeBytes(8, img_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!version_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, version_);
      }
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, name_);
      }
      if (!getTypeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, type_);
      }
      if (!getExtraDataBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, extraData_);
      }
      if (!pubKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, pubKey_);
      }
      if (!getHomeHostBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, homeHost_);
      }
      if (!img_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, img_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof ProfileInfo)) {
        return super.equals(obj);
      }
      ProfileInfo other = (ProfileInfo) obj;

      boolean result = true;
      result = result && getVersion()
          .equals(other.getVersion());
      result = result && getName()
          .equals(other.getName());
      result = result && getType()
          .equals(other.getType());
      result = result && getExtraData()
          .equals(other.getExtraData());
      result = result && getPubKey()
          .equals(other.getPubKey());
      result = result && getHomeHost()
          .equals(other.getHomeHost());
      result = result && getImg()
          .equals(other.getImg());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VERSION_FIELD_NUMBER;
      hash = (53 * hash) + getVersion().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + getType().hashCode();
      hash = (37 * hash) + EXTRADATA_FIELD_NUMBER;
      hash = (53 * hash) + getExtraData().hashCode();
      hash = (37 * hash) + PUBKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPubKey().hashCode();
      hash = (37 * hash) + HOMEHOST_FIELD_NUMBER;
      hash = (53 * hash) + getHomeHost().hashCode();
      hash = (37 * hash) + IMG_FIELD_NUMBER;
      hash = (53 * hash) + getImg().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static ProfileInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfileInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfileInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfileInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfileInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static ProfileInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static ProfileInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProfileInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProfileInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static ProfileInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static ProfileInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static ProfileInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(ProfileInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.fermat.redtooth.profiles_manager.ProfileInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.fermat.redtooth.profiles_manager.ProfileInfo)
        ProfileInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                ProfileInfo.class, Builder.class);
      }

      // Construct using org.fermat.redtooth.profiles_manager.ProfileOuterClass.ProfileInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        version_ = com.google.protobuf.ByteString.EMPTY;

        name_ = "";

        type_ = "";

        extraData_ = "";

        pubKey_ = com.google.protobuf.ByteString.EMPTY;

        homeHost_ = "";

        img_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor;
      }

      public ProfileInfo getDefaultInstanceForType() {
        return ProfileInfo.getDefaultInstance();
      }

      public ProfileInfo build() {
        ProfileInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public ProfileInfo buildPartial() {
        ProfileInfo result = new ProfileInfo(this);
        result.version_ = version_;
        result.name_ = name_;
        result.type_ = type_;
        result.extraData_ = extraData_;
        result.pubKey_ = pubKey_;
        result.homeHost_ = homeHost_;
        result.img_ = img_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof ProfileInfo) {
          return mergeFrom((ProfileInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(ProfileInfo other) {
        if (other == ProfileInfo.getDefaultInstance()) return this;
        if (other.getVersion() != com.google.protobuf.ByteString.EMPTY) {
          setVersion(other.getVersion());
        }
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getType().isEmpty()) {
          type_ = other.type_;
          onChanged();
        }
        if (!other.getExtraData().isEmpty()) {
          extraData_ = other.extraData_;
          onChanged();
        }
        if (other.getPubKey() != com.google.protobuf.ByteString.EMPTY) {
          setPubKey(other.getPubKey());
        }
        if (!other.getHomeHost().isEmpty()) {
          homeHost_ = other.homeHost_;
          onChanged();
        }
        if (other.getImg() != com.google.protobuf.ByteString.EMPTY) {
          setImg(other.getImg());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        ProfileInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (ProfileInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString version_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes version = 1;</code>
       */
      public com.google.protobuf.ByteString getVersion() {
        return version_;
      }
      /**
       * <code>bytes version = 1;</code>
       */
      public Builder setVersion(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        version_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes version = 1;</code>
       */
      public Builder clearVersion() {
        
        version_ = getDefaultInstance().getVersion();
        onChanged();
        return this;
      }

      private Object name_ = "";
      /**
       * <code>string name = 2;</code>
       */
      public String getName() {
        Object ref = name_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setName(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private Object type_ = "";
      /**
       * <code>string type = 3;</code>
       */
      public String getType() {
        Object ref = type_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          type_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public com.google.protobuf.ByteString
          getTypeBytes() {
        Object ref = type_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          type_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setType(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder clearType() {
        
        type_ = getDefaultInstance().getType();
        onChanged();
        return this;
      }
      /**
       * <code>string type = 3;</code>
       */
      public Builder setTypeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        type_ = value;
        onChanged();
        return this;
      }

      private Object extraData_ = "";
      /**
       * <code>string extraData = 4;</code>
       */
      public String getExtraData() {
        Object ref = extraData_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          extraData_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string extraData = 4;</code>
       */
      public com.google.protobuf.ByteString
          getExtraDataBytes() {
        Object ref = extraData_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          extraData_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string extraData = 4;</code>
       */
      public Builder setExtraData(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        extraData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string extraData = 4;</code>
       */
      public Builder clearExtraData() {
        
        extraData_ = getDefaultInstance().getExtraData();
        onChanged();
        return this;
      }
      /**
       * <code>string extraData = 4;</code>
       */
      public Builder setExtraDataBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        extraData_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString pubKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes pubKey = 6;</code>
       */
      public com.google.protobuf.ByteString getPubKey() {
        return pubKey_;
      }
      /**
       * <code>bytes pubKey = 6;</code>
       */
      public Builder setPubKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        pubKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes pubKey = 6;</code>
       */
      public Builder clearPubKey() {
        
        pubKey_ = getDefaultInstance().getPubKey();
        onChanged();
        return this;
      }

      private Object homeHost_ = "";
      /**
       * <code>string homeHost = 7;</code>
       */
      public String getHomeHost() {
        Object ref = homeHost_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          homeHost_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string homeHost = 7;</code>
       */
      public com.google.protobuf.ByteString
          getHomeHostBytes() {
        Object ref = homeHost_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          homeHost_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string homeHost = 7;</code>
       */
      public Builder setHomeHost(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        homeHost_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string homeHost = 7;</code>
       */
      public Builder clearHomeHost() {
        
        homeHost_ = getDefaultInstance().getHomeHost();
        onChanged();
        return this;
      }
      /**
       * <code>string homeHost = 7;</code>
       */
      public Builder setHomeHostBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        homeHost_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString img_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes img = 8;</code>
       */
      public com.google.protobuf.ByteString getImg() {
        return img_;
      }
      /**
       * <code>bytes img = 8;</code>
       */
      public Builder setImg(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        img_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes img = 8;</code>
       */
      public Builder clearImg() {
        
        img_ = getDefaultInstance().getImg();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.fermat.redtooth.profiles_manager.ProfileInfo)
    }

    // @@protoc_insertion_point(class_scope:org.fermat.redtooth.profiles_manager.ProfileInfo)
    private static final ProfileInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new ProfileInfo();
    }

    public static ProfileInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ProfileInfo>
        PARSER = new com.google.protobuf.AbstractParser<ProfileInfo>() {
      public ProfileInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new ProfileInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ProfileInfo> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<ProfileInfo> getParserForType() {
      return PARSER;
    }

    public ProfileInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProfileOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.fermat.redtooth.profiles_manager.Profile)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    boolean hasProfileInfo();
    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    ProfileInfo getProfileInfo();
    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    ProfileInfoOrBuilder getProfileInfoOrBuilder();

    /**
     * <code>bytes privKey = 2;</code>
     */
    com.google.protobuf.ByteString getPrivKey();
  }
  /**
   * Protobuf type {@code org.fermat.redtooth.profiles_manager.Profile}
   */
  public  static final class Profile extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.fermat.redtooth.profiles_manager.Profile)
      ProfileOrBuilder {
    // Use Profile.newBuilder() to construct.
    private Profile(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Profile() {
      privKey_ = com.google.protobuf.ByteString.EMPTY;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Profile(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              ProfileInfo.Builder subBuilder = null;
              if (profileInfo_ != null) {
                subBuilder = profileInfo_.toBuilder();
              }
              profileInfo_ = input.readMessage(ProfileInfo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(profileInfo_);
                profileInfo_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {

              privKey_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Profile_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Profile.class, Builder.class);
    }

    public static final int PROFILEINFO_FIELD_NUMBER = 1;
    private ProfileInfo profileInfo_;
    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    public boolean hasProfileInfo() {
      return profileInfo_ != null;
    }
    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    public ProfileInfo getProfileInfo() {
      return profileInfo_ == null ? ProfileInfo.getDefaultInstance() : profileInfo_;
    }
    /**
     * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
     */
    public ProfileInfoOrBuilder getProfileInfoOrBuilder() {
      return getProfileInfo();
    }

    public static final int PRIVKEY_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString privKey_;
    /**
     * <code>bytes privKey = 2;</code>
     */
    public com.google.protobuf.ByteString getPrivKey() {
      return privKey_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (profileInfo_ != null) {
        output.writeMessage(1, getProfileInfo());
      }
      if (!privKey_.isEmpty()) {
        output.writeBytes(2, privKey_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (profileInfo_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProfileInfo());
      }
      if (!privKey_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, privKey_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Profile)) {
        return super.equals(obj);
      }
      Profile other = (Profile) obj;

      boolean result = true;
      result = result && (hasProfileInfo() == other.hasProfileInfo());
      if (hasProfileInfo()) {
        result = result && getProfileInfo()
            .equals(other.getProfileInfo());
      }
      result = result && getPrivKey()
          .equals(other.getPrivKey());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProfileInfo()) {
        hash = (37 * hash) + PROFILEINFO_FIELD_NUMBER;
        hash = (53 * hash) + getProfileInfo().hashCode();
      }
      hash = (37 * hash) + PRIVKEY_FIELD_NUMBER;
      hash = (53 * hash) + getPrivKey().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Profile parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Profile parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Profile parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Profile parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Profile parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Profile parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Profile parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Profile parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Profile parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Profile parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Profile parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Profile parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Profile prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.fermat.redtooth.profiles_manager.Profile}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.fermat.redtooth.profiles_manager.Profile)
        ProfileOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Profile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Profile.class, Builder.class);
      }

      // Construct using org.fermat.redtooth.profiles_manager.ProfileOuterClass.Profile.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (profileInfoBuilder_ == null) {
          profileInfo_ = null;
        } else {
          profileInfo_ = null;
          profileInfoBuilder_ = null;
        }
        privKey_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor;
      }

      public Profile getDefaultInstanceForType() {
        return Profile.getDefaultInstance();
      }

      public Profile build() {
        Profile result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Profile buildPartial() {
        Profile result = new Profile(this);
        if (profileInfoBuilder_ == null) {
          result.profileInfo_ = profileInfo_;
        } else {
          result.profileInfo_ = profileInfoBuilder_.build();
        }
        result.privKey_ = privKey_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Profile) {
          return mergeFrom((Profile)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Profile other) {
        if (other == Profile.getDefaultInstance()) return this;
        if (other.hasProfileInfo()) {
          mergeProfileInfo(other.getProfileInfo());
        }
        if (other.getPrivKey() != com.google.protobuf.ByteString.EMPTY) {
          setPrivKey(other.getPrivKey());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Profile parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Profile) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private ProfileInfo profileInfo_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder> profileInfoBuilder_;
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public boolean hasProfileInfo() {
        return profileInfoBuilder_ != null || profileInfo_ != null;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public ProfileInfo getProfileInfo() {
        if (profileInfoBuilder_ == null) {
          return profileInfo_ == null ? ProfileInfo.getDefaultInstance() : profileInfo_;
        } else {
          return profileInfoBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public Builder setProfileInfo(ProfileInfo value) {
        if (profileInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          profileInfo_ = value;
          onChanged();
        } else {
          profileInfoBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public Builder setProfileInfo(
          ProfileInfo.Builder builderForValue) {
        if (profileInfoBuilder_ == null) {
          profileInfo_ = builderForValue.build();
          onChanged();
        } else {
          profileInfoBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public Builder mergeProfileInfo(ProfileInfo value) {
        if (profileInfoBuilder_ == null) {
          if (profileInfo_ != null) {
            profileInfo_ =
              ProfileInfo.newBuilder(profileInfo_).mergeFrom(value).buildPartial();
          } else {
            profileInfo_ = value;
          }
          onChanged();
        } else {
          profileInfoBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public Builder clearProfileInfo() {
        if (profileInfoBuilder_ == null) {
          profileInfo_ = null;
          onChanged();
        } else {
          profileInfo_ = null;
          profileInfoBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public ProfileInfo.Builder getProfileInfoBuilder() {
        
        onChanged();
        return getProfileInfoFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      public ProfileInfoOrBuilder getProfileInfoOrBuilder() {
        if (profileInfoBuilder_ != null) {
          return profileInfoBuilder_.getMessageOrBuilder();
        } else {
          return profileInfo_ == null ?
              ProfileInfo.getDefaultInstance() : profileInfo_;
        }
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.ProfileInfo profileInfo = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder>
          getProfileInfoFieldBuilder() {
        if (profileInfoBuilder_ == null) {
          profileInfoBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder>(
                  getProfileInfo(),
                  getParentForChildren(),
                  isClean());
          profileInfo_ = null;
        }
        return profileInfoBuilder_;
      }

      private com.google.protobuf.ByteString privKey_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>bytes privKey = 2;</code>
       */
      public com.google.protobuf.ByteString getPrivKey() {
        return privKey_;
      }
      /**
       * <code>bytes privKey = 2;</code>
       */
      public Builder setPrivKey(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        privKey_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bytes privKey = 2;</code>
       */
      public Builder clearPrivKey() {
        
        privKey_ = getDefaultInstance().getPrivKey();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.fermat.redtooth.profiles_manager.Profile)
    }

    // @@protoc_insertion_point(class_scope:org.fermat.redtooth.profiles_manager.Profile)
    private static final Profile DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Profile();
    }

    public static Profile getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Profile>
        PARSER = new com.google.protobuf.AbstractParser<Profile>() {
      public Profile parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Profile(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Profile> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Profile> getParserForType() {
      return PARSER;
    }

    public Profile getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WrapperOrBuilder extends
      // @@protoc_insertion_point(interface_extends:org.fermat.redtooth.profiles_manager.Wrapper)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    boolean hasProfile();
    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    Profile getProfile();
    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    ProfileOrBuilder getProfileOrBuilder();

    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    java.util.List<ProfileInfo>
        getProfilesInfoList();
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    ProfileInfo getProfilesInfo(int index);
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    int getProfilesInfoCount();
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    java.util.List<? extends ProfileInfoOrBuilder>
        getProfilesInfoOrBuilderList();
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    ProfileInfoOrBuilder getProfilesInfoOrBuilder(
            int index);
  }
  /**
   * Protobuf type {@code org.fermat.redtooth.profiles_manager.Wrapper}
   */
  public  static final class Wrapper extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:org.fermat.redtooth.profiles_manager.Wrapper)
      WrapperOrBuilder {
    // Use Wrapper.newBuilder() to construct.
    private Wrapper(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Wrapper() {
      profilesInfo_ = java.util.Collections.emptyList();
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private Wrapper(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              Profile.Builder subBuilder = null;
              if (profile_ != null) {
                subBuilder = profile_.toBuilder();
              }
              profile_ = input.readMessage(Profile.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(profile_);
                profile_ = subBuilder.buildPartial();
              }

              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                profilesInfo_ = new java.util.ArrayList<ProfileInfo>();
                mutable_bitField0_ |= 0x00000002;
              }
              profilesInfo_.add(
                  input.readMessage(ProfileInfo.parser(), extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          profilesInfo_ = java.util.Collections.unmodifiableList(profilesInfo_);
        }
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Wrapper_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Wrapper.class, Builder.class);
    }

    private int bitField0_;
    public static final int PROFILE_FIELD_NUMBER = 1;
    private Profile profile_;
    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    public boolean hasProfile() {
      return profile_ != null;
    }
    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    public Profile getProfile() {
      return profile_ == null ? Profile.getDefaultInstance() : profile_;
    }
    /**
     * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
     */
    public ProfileOrBuilder getProfileOrBuilder() {
      return getProfile();
    }

    public static final int PROFILESINFO_FIELD_NUMBER = 2;
    private java.util.List<ProfileInfo> profilesInfo_;
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    public java.util.List<ProfileInfo> getProfilesInfoList() {
      return profilesInfo_;
    }
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    public java.util.List<? extends ProfileInfoOrBuilder>
        getProfilesInfoOrBuilderList() {
      return profilesInfo_;
    }
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    public int getProfilesInfoCount() {
      return profilesInfo_.size();
    }
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    public ProfileInfo getProfilesInfo(int index) {
      return profilesInfo_.get(index);
    }
    /**
     * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
     */
    public ProfileInfoOrBuilder getProfilesInfoOrBuilder(
        int index) {
      return profilesInfo_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (profile_ != null) {
        output.writeMessage(1, getProfile());
      }
      for (int i = 0; i < profilesInfo_.size(); i++) {
        output.writeMessage(2, profilesInfo_.get(i));
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (profile_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getProfile());
      }
      for (int i = 0; i < profilesInfo_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, profilesInfo_.get(i));
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Wrapper)) {
        return super.equals(obj);
      }
      Wrapper other = (Wrapper) obj;

      boolean result = true;
      result = result && (hasProfile() == other.hasProfile());
      if (hasProfile()) {
        result = result && getProfile()
            .equals(other.getProfile());
      }
      result = result && getProfilesInfoList()
          .equals(other.getProfilesInfoList());
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasProfile()) {
        hash = (37 * hash) + PROFILE_FIELD_NUMBER;
        hash = (53 * hash) + getProfile().hashCode();
      }
      if (getProfilesInfoCount() > 0) {
        hash = (37 * hash) + PROFILESINFO_FIELD_NUMBER;
        hash = (53 * hash) + getProfilesInfoList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Wrapper parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Wrapper parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Wrapper parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Wrapper parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Wrapper parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Wrapper parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Wrapper parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Wrapper parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Wrapper parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Wrapper parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Wrapper parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Wrapper prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code org.fermat.redtooth.profiles_manager.Wrapper}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:org.fermat.redtooth.profiles_manager.Wrapper)
        WrapperOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Wrapper_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Wrapper.class, Builder.class);
      }

      // Construct using org.fermat.redtooth.profiles_manager.ProfileOuterClass.Wrapper.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getProfilesInfoFieldBuilder();
        }
      }
      public Builder clear() {
        super.clear();
        if (profileBuilder_ == null) {
          profile_ = null;
        } else {
          profile_ = null;
          profileBuilder_ = null;
        }
        if (profilesInfoBuilder_ == null) {
          profilesInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          profilesInfoBuilder_.clear();
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return ProfileOuterClass.internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor;
      }

      public Wrapper getDefaultInstanceForType() {
        return Wrapper.getDefaultInstance();
      }

      public Wrapper build() {
        Wrapper result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Wrapper buildPartial() {
        Wrapper result = new Wrapper(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (profileBuilder_ == null) {
          result.profile_ = profile_;
        } else {
          result.profile_ = profileBuilder_.build();
        }
        if (profilesInfoBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002)) {
            profilesInfo_ = java.util.Collections.unmodifiableList(profilesInfo_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.profilesInfo_ = profilesInfo_;
        } else {
          result.profilesInfo_ = profilesInfoBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Wrapper) {
          return mergeFrom((Wrapper)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Wrapper other) {
        if (other == Wrapper.getDefaultInstance()) return this;
        if (other.hasProfile()) {
          mergeProfile(other.getProfile());
        }
        if (profilesInfoBuilder_ == null) {
          if (!other.profilesInfo_.isEmpty()) {
            if (profilesInfo_.isEmpty()) {
              profilesInfo_ = other.profilesInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureProfilesInfoIsMutable();
              profilesInfo_.addAll(other.profilesInfo_);
            }
            onChanged();
          }
        } else {
          if (!other.profilesInfo_.isEmpty()) {
            if (profilesInfoBuilder_.isEmpty()) {
              profilesInfoBuilder_.dispose();
              profilesInfoBuilder_ = null;
              profilesInfo_ = other.profilesInfo_;
              bitField0_ = (bitField0_ & ~0x00000002);
              profilesInfoBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getProfilesInfoFieldBuilder() : null;
            } else {
              profilesInfoBuilder_.addAllMessages(other.profilesInfo_);
            }
          }
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Wrapper parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Wrapper) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private Profile profile_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          Profile, Profile.Builder, ProfileOrBuilder> profileBuilder_;
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public boolean hasProfile() {
        return profileBuilder_ != null || profile_ != null;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Profile getProfile() {
        if (profileBuilder_ == null) {
          return profile_ == null ? Profile.getDefaultInstance() : profile_;
        } else {
          return profileBuilder_.getMessage();
        }
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Builder setProfile(Profile value) {
        if (profileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          profile_ = value;
          onChanged();
        } else {
          profileBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Builder setProfile(
          Profile.Builder builderForValue) {
        if (profileBuilder_ == null) {
          profile_ = builderForValue.build();
          onChanged();
        } else {
          profileBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Builder mergeProfile(Profile value) {
        if (profileBuilder_ == null) {
          if (profile_ != null) {
            profile_ =
              Profile.newBuilder(profile_).mergeFrom(value).buildPartial();
          } else {
            profile_ = value;
          }
          onChanged();
        } else {
          profileBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Builder clearProfile() {
        if (profileBuilder_ == null) {
          profile_ = null;
          onChanged();
        } else {
          profile_ = null;
          profileBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public Profile.Builder getProfileBuilder() {
        
        onChanged();
        return getProfileFieldBuilder().getBuilder();
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      public ProfileOrBuilder getProfileOrBuilder() {
        if (profileBuilder_ != null) {
          return profileBuilder_.getMessageOrBuilder();
        } else {
          return profile_ == null ?
              Profile.getDefaultInstance() : profile_;
        }
      }
      /**
       * <code>.org.fermat.redtooth.profiles_manager.Profile profile = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Profile, Profile.Builder, ProfileOrBuilder>
          getProfileFieldBuilder() {
        if (profileBuilder_ == null) {
          profileBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Profile, Profile.Builder, ProfileOrBuilder>(
                  getProfile(),
                  getParentForChildren(),
                  isClean());
          profile_ = null;
        }
        return profileBuilder_;
      }

      private java.util.List<ProfileInfo> profilesInfo_ =
        java.util.Collections.emptyList();
      private void ensureProfilesInfoIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          profilesInfo_ = new java.util.ArrayList<ProfileInfo>(profilesInfo_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder> profilesInfoBuilder_;

      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public java.util.List<ProfileInfo> getProfilesInfoList() {
        if (profilesInfoBuilder_ == null) {
          return java.util.Collections.unmodifiableList(profilesInfo_);
        } else {
          return profilesInfoBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public int getProfilesInfoCount() {
        if (profilesInfoBuilder_ == null) {
          return profilesInfo_.size();
        } else {
          return profilesInfoBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public ProfileInfo getProfilesInfo(int index) {
        if (profilesInfoBuilder_ == null) {
          return profilesInfo_.get(index);
        } else {
          return profilesInfoBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder setProfilesInfo(
          int index, ProfileInfo value) {
        if (profilesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesInfoIsMutable();
          profilesInfo_.set(index, value);
          onChanged();
        } else {
          profilesInfoBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder setProfilesInfo(
          int index, ProfileInfo.Builder builderForValue) {
        if (profilesInfoBuilder_ == null) {
          ensureProfilesInfoIsMutable();
          profilesInfo_.set(index, builderForValue.build());
          onChanged();
        } else {
          profilesInfoBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder addProfilesInfo(ProfileInfo value) {
        if (profilesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesInfoIsMutable();
          profilesInfo_.add(value);
          onChanged();
        } else {
          profilesInfoBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder addProfilesInfo(
          int index, ProfileInfo value) {
        if (profilesInfoBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureProfilesInfoIsMutable();
          profilesInfo_.add(index, value);
          onChanged();
        } else {
          profilesInfoBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder addProfilesInfo(
          ProfileInfo.Builder builderForValue) {
        if (profilesInfoBuilder_ == null) {
          ensureProfilesInfoIsMutable();
          profilesInfo_.add(builderForValue.build());
          onChanged();
        } else {
          profilesInfoBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder addProfilesInfo(
          int index, ProfileInfo.Builder builderForValue) {
        if (profilesInfoBuilder_ == null) {
          ensureProfilesInfoIsMutable();
          profilesInfo_.add(index, builderForValue.build());
          onChanged();
        } else {
          profilesInfoBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder addAllProfilesInfo(
          Iterable<? extends ProfileInfo> values) {
        if (profilesInfoBuilder_ == null) {
          ensureProfilesInfoIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, profilesInfo_);
          onChanged();
        } else {
          profilesInfoBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder clearProfilesInfo() {
        if (profilesInfoBuilder_ == null) {
          profilesInfo_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          profilesInfoBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public Builder removeProfilesInfo(int index) {
        if (profilesInfoBuilder_ == null) {
          ensureProfilesInfoIsMutable();
          profilesInfo_.remove(index);
          onChanged();
        } else {
          profilesInfoBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public ProfileInfo.Builder getProfilesInfoBuilder(
          int index) {
        return getProfilesInfoFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public ProfileInfoOrBuilder getProfilesInfoOrBuilder(
          int index) {
        if (profilesInfoBuilder_ == null) {
          return profilesInfo_.get(index);  } else {
          return profilesInfoBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public java.util.List<? extends ProfileInfoOrBuilder>
           getProfilesInfoOrBuilderList() {
        if (profilesInfoBuilder_ != null) {
          return profilesInfoBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(profilesInfo_);
        }
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public ProfileInfo.Builder addProfilesInfoBuilder() {
        return getProfilesInfoFieldBuilder().addBuilder(
            ProfileInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public ProfileInfo.Builder addProfilesInfoBuilder(
          int index) {
        return getProfilesInfoFieldBuilder().addBuilder(
            index, ProfileInfo.getDefaultInstance());
      }
      /**
       * <code>repeated .org.fermat.redtooth.profiles_manager.ProfileInfo profilesInfo = 2;</code>
       */
      public java.util.List<ProfileInfo.Builder>
           getProfilesInfoBuilderList() {
        return getProfilesInfoFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder>
          getProfilesInfoFieldBuilder() {
        if (profilesInfoBuilder_ == null) {
          profilesInfoBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              ProfileInfo, ProfileInfo.Builder, ProfileInfoOrBuilder>(
                  profilesInfo_,
                  ((bitField0_ & 0x00000002) == 0x00000002),
                  getParentForChildren(),
                  isClean());
          profilesInfo_ = null;
        }
        return profilesInfoBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:org.fermat.redtooth.profiles_manager.Wrapper)
    }

    // @@protoc_insertion_point(class_scope:org.fermat.redtooth.profiles_manager.Wrapper)
    private static final Wrapper DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Wrapper();
    }

    public static Wrapper getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Wrapper>
        PARSER = new com.google.protobuf.AbstractParser<Wrapper>() {
      public Wrapper parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new Wrapper(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Wrapper> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Wrapper> getParserForType() {
      return PARSER;
    }

    public Wrapper getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fermat_redtooth_profiles_manager_Profile_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_org_fermat_redtooth_profiles_manager_Wrapper_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\rprofile.proto\022$org.fermat.redtooth.pro" +
      "files_manager\"|\n\013ProfileInfo\022\017\n\007version\030" +
      "\001 \001(\014\022\014\n\004name\030\002 \001(\t\022\014\n\004type\030\003 \001(\t\022\021\n\text" +
      "raData\030\004 \001(\t\022\016\n\006pubKey\030\006 \001(\014\022\020\n\010homeHost" +
      "\030\007 \001(\t\022\013\n\003img\030\010 \001(\014\"b\n\007Profile\022F\n\013profil" +
      "eInfo\030\001 \001(\01321.org.fermat.redtooth.profil" +
      "es_manager.ProfileInfo\022\017\n\007privKey\030\002 \001(\014\"" +
      "\222\001\n\007Wrapper\022>\n\007profile\030\001 \001(\0132-.org.ferma" +
      "t.redtooth.profiles_manager.Profile\022G\n\014p" +
      "rofilesInfo\030\002 \003(\01321.org.fermat.redtooth.",
      "profiles_manager.ProfileInfob\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fermat_redtooth_profiles_manager_ProfileInfo_descriptor,
        new String[] { "Version", "Name", "Type", "ExtraData", "PubKey", "HomeHost", "Img", });
    internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_org_fermat_redtooth_profiles_manager_Profile_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fermat_redtooth_profiles_manager_Profile_descriptor,
        new String[] { "ProfileInfo", "PrivKey", });
    internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_org_fermat_redtooth_profiles_manager_Wrapper_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_org_fermat_redtooth_profiles_manager_Wrapper_descriptor,
        new String[] { "Profile", "ProfilesInfo", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
