// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: IopCan.proto

package org.fermat.redtooth.profile_server.protocol;

public final class IopCan {
  private IopCan() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface CanIpnsEntryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CanIpnsEntry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * IPFS path string converted to byte array. The path string has to be "/ipfs/$objectHashEncoded",
     * </pre>
     *
     * <code>optional bytes value = 1;</code>
     */
    com.google.protobuf.ByteString getValue();

    /**
     * <pre>
     * where $objectHashEncoded is base58 encoded hash of the CAN object that the client received as `CanStoreDataResponse.hash`.
     * The base58 encoding must be used without the multibase prefix - for example "/ipfs/QmaRvpLT4RgBDVY6cQKwqQGQNtbM31KSqh8TxvQgFoEUus".
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     */
    com.google.protobuf.ByteString getSignature();

    /**
     * <pre>
     * Type of meaning of 'validity' field.
     * </pre>
     *
     * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
     */
    int getValidityTypeValue();
    /**
     * <pre>
     * Type of meaning of 'validity' field.
     * </pre>
     *
     * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
     */
    IopCan.CanIpnsEntry.ValidityType getValidityType();

    /**
     * <pre>
     * RFC3339 UTF-8 string converted to byte array.
     * </pre>
     *
     * <code>optional bytes validity = 4;</code>
     */
    com.google.protobuf.ByteString getValidity();

    /**
     * <pre>
     * Record sequence number that has to be increased on updates.
     * </pre>
     *
     * <code>optional uint64 sequence = 5;</code>
     */
    long getSequence();

    /**
     * <pre>
     * Time to live of the IPNS record in cache in nanoseconds.
     * </pre>
     *
     * <code>optional uint64 ttl = 6;</code>
     */
    long getTtl();
  }
  /**
   * <pre>
   * IPNS record as defined in https://github.com/DeCentral-Budapest/go-ipfs/blob/master/namesys/pb/namesys.proto
   * </pre>
   *
   * Protobuf type {@code CanIpnsEntry}
   */
  public  static final class CanIpnsEntry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CanIpnsEntry)
      CanIpnsEntryOrBuilder {
    // Use CanIpnsEntry.newBuilder() to construct.
    private CanIpnsEntry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CanIpnsEntry() {
      value_ = com.google.protobuf.ByteString.EMPTY;
      signature_ = com.google.protobuf.ByteString.EMPTY;
      validityType_ = 0;
      validity_ = com.google.protobuf.ByteString.EMPTY;
      sequence_ = 0L;
      ttl_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CanIpnsEntry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 10: {

              value_ = input.readBytes();
              break;
            }
            case 18: {

              signature_ = input.readBytes();
              break;
            }
            case 24: {
              int rawValue = input.readEnum();

              validityType_ = rawValue;
              break;
            }
            case 34: {

              validity_ = input.readBytes();
              break;
            }
            case 40: {

              sequence_ = input.readUInt64();
              break;
            }
            case 48: {

              ttl_ = input.readUInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IopCan.internal_static_CanIpnsEntry_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IopCan.internal_static_CanIpnsEntry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IopCan.CanIpnsEntry.class, IopCan.CanIpnsEntry.Builder.class);
    }

    /**
     * <pre>
     * Type of validity value.
     * </pre>
     *
     * Protobuf enum {@code CanIpnsEntry.ValidityType}
     */
    public enum ValidityType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <pre>
       * Validity value is specifies a time until which the IPNS record is valid.
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      EOL(0),
      UNRECOGNIZED(-1),
      ;

      /**
       * <pre>
       * Validity value is specifies a time until which the IPNS record is valid.
       * </pre>
       *
       * <code>EOL = 0;</code>
       */
      public static final int EOL_VALUE = 0;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static ValidityType valueOf(int value) {
        return forNumber(value);
      }

      public static ValidityType forNumber(int value) {
        switch (value) {
          case 0: return EOL;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<ValidityType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          ValidityType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<ValidityType>() {
              public ValidityType findValueByNumber(int number) {
                return ValidityType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return IopCan.CanIpnsEntry.getDescriptor().getEnumTypes().get(0);
      }

      private static final ValidityType[] VALUES = values();

      public static ValidityType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private ValidityType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CanIpnsEntry.ValidityType)
    }

    public static final int VALUE_FIELD_NUMBER = 1;
    private com.google.protobuf.ByteString value_;
    /**
     * <pre>
     * IPFS path string converted to byte array. The path string has to be "/ipfs/$objectHashEncoded",
     * </pre>
     *
     * <code>optional bytes value = 1;</code>
     */
    public com.google.protobuf.ByteString getValue() {
      return value_;
    }

    public static final int SIGNATURE_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString signature_;
    /**
     * <pre>
     * where $objectHashEncoded is base58 encoded hash of the CAN object that the client received as `CanStoreDataResponse.hash`.
     * The base58 encoding must be used without the multibase prefix - for example "/ipfs/QmaRvpLT4RgBDVY6cQKwqQGQNtbM31KSqh8TxvQgFoEUus".
     * </pre>
     *
     * <code>optional bytes signature = 2;</code>
     */
    public com.google.protobuf.ByteString getSignature() {
      return signature_;
    }

    public static final int VALIDITYTYPE_FIELD_NUMBER = 3;
    private int validityType_;
    /**
     * <pre>
     * Type of meaning of 'validity' field.
     * </pre>
     *
     * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
     */
    public int getValidityTypeValue() {
      return validityType_;
    }
    /**
     * <pre>
     * Type of meaning of 'validity' field.
     * </pre>
     *
     * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
     */
    public IopCan.CanIpnsEntry.ValidityType getValidityType() {
      IopCan.CanIpnsEntry.ValidityType result = IopCan.CanIpnsEntry.ValidityType.valueOf(validityType_);
      return result == null ? IopCan.CanIpnsEntry.ValidityType.UNRECOGNIZED : result;
    }

    public static final int VALIDITY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString validity_;
    /**
     * <pre>
     * RFC3339 UTF-8 string converted to byte array.
     * </pre>
     *
     * <code>optional bytes validity = 4;</code>
     */
    public com.google.protobuf.ByteString getValidity() {
      return validity_;
    }

    public static final int SEQUENCE_FIELD_NUMBER = 5;
    private long sequence_;
    /**
     * <pre>
     * Record sequence number that has to be increased on updates.
     * </pre>
     *
     * <code>optional uint64 sequence = 5;</code>
     */
    public long getSequence() {
      return sequence_;
    }

    public static final int TTL_FIELD_NUMBER = 6;
    private long ttl_;
    /**
     * <pre>
     * Time to live of the IPNS record in cache in nanoseconds.
     * </pre>
     *
     * <code>optional uint64 ttl = 6;</code>
     */
    public long getTtl() {
      return ttl_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!value_.isEmpty()) {
        output.writeBytes(1, value_);
      }
      if (!signature_.isEmpty()) {
        output.writeBytes(2, signature_);
      }
      if (validityType_ != IopCan.CanIpnsEntry.ValidityType.EOL.getNumber()) {
        output.writeEnum(3, validityType_);
      }
      if (!validity_.isEmpty()) {
        output.writeBytes(4, validity_);
      }
      if (sequence_ != 0L) {
        output.writeUInt64(5, sequence_);
      }
      if (ttl_ != 0L) {
        output.writeUInt64(6, ttl_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!value_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, value_);
      }
      if (!signature_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, signature_);
      }
      if (validityType_ != IopCan.CanIpnsEntry.ValidityType.EOL.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(3, validityType_);
      }
      if (!validity_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, validity_);
      }
      if (sequence_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(5, sequence_);
      }
      if (ttl_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt64Size(6, ttl_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IopCan.CanIpnsEntry)) {
        return super.equals(obj);
      }
      IopCan.CanIpnsEntry other = (IopCan.CanIpnsEntry) obj;

      boolean result = true;
      result = result && getValue()
          .equals(other.getValue());
      result = result && getSignature()
          .equals(other.getSignature());
      result = result && validityType_ == other.validityType_;
      result = result && getValidity()
          .equals(other.getValidity());
      result = result && (getSequence()
          == other.getSequence());
      result = result && (getTtl()
          == other.getTtl());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + VALUE_FIELD_NUMBER;
      hash = (53 * hash) + getValue().hashCode();
      hash = (37 * hash) + SIGNATURE_FIELD_NUMBER;
      hash = (53 * hash) + getSignature().hashCode();
      hash = (37 * hash) + VALIDITYTYPE_FIELD_NUMBER;
      hash = (53 * hash) + validityType_;
      hash = (37 * hash) + VALIDITY_FIELD_NUMBER;
      hash = (53 * hash) + getValidity().hashCode();
      hash = (37 * hash) + SEQUENCE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getSequence());
      hash = (37 * hash) + TTL_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTtl());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IopCan.CanIpnsEntry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IopCan.CanIpnsEntry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IopCan.CanIpnsEntry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IopCan.CanIpnsEntry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IopCan.CanIpnsEntry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IopCan.CanIpnsEntry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IopCan.CanIpnsEntry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IopCan.CanIpnsEntry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IopCan.CanIpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IopCan.CanIpnsEntry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IopCan.CanIpnsEntry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * IPNS record as defined in https://github.com/DeCentral-Budapest/go-ipfs/blob/master/namesys/pb/namesys.proto
     * </pre>
     *
     * Protobuf type {@code CanIpnsEntry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CanIpnsEntry)
        IopCan.CanIpnsEntryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IopCan.internal_static_CanIpnsEntry_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IopCan.internal_static_CanIpnsEntry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IopCan.CanIpnsEntry.class, IopCan.CanIpnsEntry.Builder.class);
      }

      // Construct using IopCan.CanIpnsEntry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        value_ = com.google.protobuf.ByteString.EMPTY;

        signature_ = com.google.protobuf.ByteString.EMPTY;

        validityType_ = 0;

        validity_ = com.google.protobuf.ByteString.EMPTY;

        sequence_ = 0L;

        ttl_ = 0L;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IopCan.internal_static_CanIpnsEntry_descriptor;
      }

      public IopCan.CanIpnsEntry getDefaultInstanceForType() {
        return IopCan.CanIpnsEntry.getDefaultInstance();
      }

      public IopCan.CanIpnsEntry build() {
        IopCan.CanIpnsEntry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IopCan.CanIpnsEntry buildPartial() {
        IopCan.CanIpnsEntry result = new IopCan.CanIpnsEntry(this);
        result.value_ = value_;
        result.signature_ = signature_;
        result.validityType_ = validityType_;
        result.validity_ = validity_;
        result.sequence_ = sequence_;
        result.ttl_ = ttl_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IopCan.CanIpnsEntry) {
          return mergeFrom((IopCan.CanIpnsEntry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IopCan.CanIpnsEntry other) {
        if (other == IopCan.CanIpnsEntry.getDefaultInstance()) return this;
        if (other.getValue() != com.google.protobuf.ByteString.EMPTY) {
          setValue(other.getValue());
        }
        if (other.getSignature() != com.google.protobuf.ByteString.EMPTY) {
          setSignature(other.getSignature());
        }
        if (other.validityType_ != 0) {
          setValidityTypeValue(other.getValidityTypeValue());
        }
        if (other.getValidity() != com.google.protobuf.ByteString.EMPTY) {
          setValidity(other.getValidity());
        }
        if (other.getSequence() != 0L) {
          setSequence(other.getSequence());
        }
        if (other.getTtl() != 0L) {
          setTtl(other.getTtl());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IopCan.CanIpnsEntry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IopCan.CanIpnsEntry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.google.protobuf.ByteString value_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * IPFS path string converted to byte array. The path string has to be "/ipfs/$objectHashEncoded",
       * </pre>
       *
       * <code>optional bytes value = 1;</code>
       */
      public com.google.protobuf.ByteString getValue() {
        return value_;
      }
      /**
       * <pre>
       * IPFS path string converted to byte array. The path string has to be "/ipfs/$objectHashEncoded",
       * </pre>
       *
       * <code>optional bytes value = 1;</code>
       */
      public Builder setValue(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        value_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * IPFS path string converted to byte array. The path string has to be "/ipfs/$objectHashEncoded",
       * </pre>
       *
       * <code>optional bytes value = 1;</code>
       */
      public Builder clearValue() {
        
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString signature_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * where $objectHashEncoded is base58 encoded hash of the CAN object that the client received as `CanStoreDataResponse.hash`.
       * The base58 encoding must be used without the multibase prefix - for example "/ipfs/QmaRvpLT4RgBDVY6cQKwqQGQNtbM31KSqh8TxvQgFoEUus".
       * </pre>
       *
       * <code>optional bytes signature = 2;</code>
       */
      public com.google.protobuf.ByteString getSignature() {
        return signature_;
      }
      /**
       * <pre>
       * where $objectHashEncoded is base58 encoded hash of the CAN object that the client received as `CanStoreDataResponse.hash`.
       * The base58 encoding must be used without the multibase prefix - for example "/ipfs/QmaRvpLT4RgBDVY6cQKwqQGQNtbM31KSqh8TxvQgFoEUus".
       * </pre>
       *
       * <code>optional bytes signature = 2;</code>
       */
      public Builder setSignature(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        signature_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * where $objectHashEncoded is base58 encoded hash of the CAN object that the client received as `CanStoreDataResponse.hash`.
       * The base58 encoding must be used without the multibase prefix - for example "/ipfs/QmaRvpLT4RgBDVY6cQKwqQGQNtbM31KSqh8TxvQgFoEUus".
       * </pre>
       *
       * <code>optional bytes signature = 2;</code>
       */
      public Builder clearSignature() {
        
        signature_ = getDefaultInstance().getSignature();
        onChanged();
        return this;
      }

      private int validityType_ = 0;
      /**
       * <pre>
       * Type of meaning of 'validity' field.
       * </pre>
       *
       * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
       */
      public int getValidityTypeValue() {
        return validityType_;
      }
      /**
       * <pre>
       * Type of meaning of 'validity' field.
       * </pre>
       *
       * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
       */
      public Builder setValidityTypeValue(int value) {
        validityType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of meaning of 'validity' field.
       * </pre>
       *
       * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
       */
      public IopCan.CanIpnsEntry.ValidityType getValidityType() {
        IopCan.CanIpnsEntry.ValidityType result = IopCan.CanIpnsEntry.ValidityType.valueOf(validityType_);
        return result == null ? IopCan.CanIpnsEntry.ValidityType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of meaning of 'validity' field.
       * </pre>
       *
       * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
       */
      public Builder setValidityType(IopCan.CanIpnsEntry.ValidityType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        validityType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of meaning of 'validity' field.
       * </pre>
       *
       * <code>optional .CanIpnsEntry.ValidityType validityType = 3;</code>
       */
      public Builder clearValidityType() {
        
        validityType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString validity_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * RFC3339 UTF-8 string converted to byte array.
       * </pre>
       *
       * <code>optional bytes validity = 4;</code>
       */
      public com.google.protobuf.ByteString getValidity() {
        return validity_;
      }
      /**
       * <pre>
       * RFC3339 UTF-8 string converted to byte array.
       * </pre>
       *
       * <code>optional bytes validity = 4;</code>
       */
      public Builder setValidity(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        validity_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * RFC3339 UTF-8 string converted to byte array.
       * </pre>
       *
       * <code>optional bytes validity = 4;</code>
       */
      public Builder clearValidity() {
        
        validity_ = getDefaultInstance().getValidity();
        onChanged();
        return this;
      }

      private long sequence_ ;
      /**
       * <pre>
       * Record sequence number that has to be increased on updates.
       * </pre>
       *
       * <code>optional uint64 sequence = 5;</code>
       */
      public long getSequence() {
        return sequence_;
      }
      /**
       * <pre>
       * Record sequence number that has to be increased on updates.
       * </pre>
       *
       * <code>optional uint64 sequence = 5;</code>
       */
      public Builder setSequence(long value) {
        
        sequence_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Record sequence number that has to be increased on updates.
       * </pre>
       *
       * <code>optional uint64 sequence = 5;</code>
       */
      public Builder clearSequence() {
        
        sequence_ = 0L;
        onChanged();
        return this;
      }

      private long ttl_ ;
      /**
       * <pre>
       * Time to live of the IPNS record in cache in nanoseconds.
       * </pre>
       *
       * <code>optional uint64 ttl = 6;</code>
       */
      public long getTtl() {
        return ttl_;
      }
      /**
       * <pre>
       * Time to live of the IPNS record in cache in nanoseconds.
       * </pre>
       *
       * <code>optional uint64 ttl = 6;</code>
       */
      public Builder setTtl(long value) {
        
        ttl_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Time to live of the IPNS record in cache in nanoseconds.
       * </pre>
       *
       * <code>optional uint64 ttl = 6;</code>
       */
      public Builder clearTtl() {
        
        ttl_ = 0L;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CanIpnsEntry)
    }

    // @@protoc_insertion_point(class_scope:CanIpnsEntry)
    private static final IopCan.CanIpnsEntry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IopCan.CanIpnsEntry();
    }

    public static IopCan.CanIpnsEntry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanIpnsEntry>
        PARSER = new com.google.protobuf.AbstractParser<CanIpnsEntry>() {
      public CanIpnsEntry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CanIpnsEntry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CanIpnsEntry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CanIpnsEntry> getParserForType() {
      return PARSER;
    }

    public IopCan.CanIpnsEntry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface CanCryptoKeyOrBuilder extends
      // @@protoc_insertion_point(interface_extends:CanCryptoKey)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Type of the key.
     * </pre>
     *
     * <code>optional .CanCryptoKey.KeyType type = 1;</code>
     */
    int getTypeValue();
    /**
     * <pre>
     * Type of the key.
     * </pre>
     *
     * <code>optional .CanCryptoKey.KeyType type = 1;</code>
     */
    IopCan.CanCryptoKey.KeyType getType();

    /**
     * <pre>
     * Key binary data.
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    com.google.protobuf.ByteString getData();
  }
  /**
   * <pre>
   * Representation of a cryptographic key in CAN API.
   * </pre>
   *
   * Protobuf type {@code CanCryptoKey}
   */
  public  static final class CanCryptoKey extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:CanCryptoKey)
      CanCryptoKeyOrBuilder {
    // Use CanCryptoKey.newBuilder() to construct.
    private CanCryptoKey(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private CanCryptoKey() {
      type_ = 0;
      data_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
    }
    private CanCryptoKey(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!input.skipField(tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();

              type_ = rawValue;
              break;
            }
            case 18: {

              data_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return IopCan.internal_static_CanCryptoKey_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return IopCan.internal_static_CanCryptoKey_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              IopCan.CanCryptoKey.class, IopCan.CanCryptoKey.Builder.class);
    }

    /**
     * <pre>
     * Type of the key algorithm. 
     * </pre>
     *
     * Protobuf enum {@code CanCryptoKey.KeyType}
     */
    public enum KeyType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>RSA = 0;</code>
       */
      RSA(0),
      /**
       * <code>Ed25519 = 1;</code>
       */
      Ed25519(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>RSA = 0;</code>
       */
      public static final int RSA_VALUE = 0;
      /**
       * <code>Ed25519 = 1;</code>
       */
      public static final int Ed25519_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new java.lang.IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @java.lang.Deprecated
      public static KeyType valueOf(int value) {
        return forNumber(value);
      }

      public static KeyType forNumber(int value) {
        switch (value) {
          case 0: return RSA;
          case 1: return Ed25519;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<KeyType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          KeyType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<KeyType>() {
              public KeyType findValueByNumber(int number) {
                return KeyType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return IopCan.CanCryptoKey.getDescriptor().getEnumTypes().get(0);
      }

      private static final KeyType[] VALUES = values();

      public static KeyType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private KeyType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:CanCryptoKey.KeyType)
    }

    public static final int TYPE_FIELD_NUMBER = 1;
    private int type_;
    /**
     * <pre>
     * Type of the key.
     * </pre>
     *
     * <code>optional .CanCryptoKey.KeyType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <pre>
     * Type of the key.
     * </pre>
     *
     * <code>optional .CanCryptoKey.KeyType type = 1;</code>
     */
    public IopCan.CanCryptoKey.KeyType getType() {
      IopCan.CanCryptoKey.KeyType result = IopCan.CanCryptoKey.KeyType.valueOf(type_);
      return result == null ? IopCan.CanCryptoKey.KeyType.UNRECOGNIZED : result;
    }

    public static final int DATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString data_;
    /**
     * <pre>
     * Key binary data.
     * </pre>
     *
     * <code>optional bytes data = 2;</code>
     */
    public com.google.protobuf.ByteString getData() {
      return data_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (type_ != IopCan.CanCryptoKey.KeyType.RSA.getNumber()) {
        output.writeEnum(1, type_);
      }
      if (!data_.isEmpty()) {
        output.writeBytes(2, data_);
      }
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (type_ != IopCan.CanCryptoKey.KeyType.RSA.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_);
      }
      if (!data_.isEmpty()) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, data_);
      }
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof IopCan.CanCryptoKey)) {
        return super.equals(obj);
      }
      IopCan.CanCryptoKey other = (IopCan.CanCryptoKey) obj;

      boolean result = true;
      result = result && type_ == other.type_;
      result = result && getData()
          .equals(other.getData());
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      hash = (37 * hash) + TYPE_FIELD_NUMBER;
      hash = (53 * hash) + type_;
      hash = (37 * hash) + DATA_FIELD_NUMBER;
      hash = (53 * hash) + getData().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static IopCan.CanCryptoKey parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IopCan.CanCryptoKey parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IopCan.CanCryptoKey parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static IopCan.CanCryptoKey parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static IopCan.CanCryptoKey parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IopCan.CanCryptoKey parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static IopCan.CanCryptoKey parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static IopCan.CanCryptoKey parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static IopCan.CanCryptoKey parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static IopCan.CanCryptoKey parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(IopCan.CanCryptoKey prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Representation of a cryptographic key in CAN API.
     * </pre>
     *
     * Protobuf type {@code CanCryptoKey}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:CanCryptoKey)
        IopCan.CanCryptoKeyOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return IopCan.internal_static_CanCryptoKey_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return IopCan.internal_static_CanCryptoKey_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                IopCan.CanCryptoKey.class, IopCan.CanCryptoKey.Builder.class);
      }

      // Construct using IopCan.CanCryptoKey.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        type_ = 0;

        data_ = com.google.protobuf.ByteString.EMPTY;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return IopCan.internal_static_CanCryptoKey_descriptor;
      }

      public IopCan.CanCryptoKey getDefaultInstanceForType() {
        return IopCan.CanCryptoKey.getDefaultInstance();
      }

      public IopCan.CanCryptoKey build() {
        IopCan.CanCryptoKey result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public IopCan.CanCryptoKey buildPartial() {
        IopCan.CanCryptoKey result = new IopCan.CanCryptoKey(this);
        result.type_ = type_;
        result.data_ = data_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof IopCan.CanCryptoKey) {
          return mergeFrom((IopCan.CanCryptoKey)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(IopCan.CanCryptoKey other) {
        if (other == IopCan.CanCryptoKey.getDefaultInstance()) return this;
        if (other.type_ != 0) {
          setTypeValue(other.getTypeValue());
        }
        if (other.getData() != com.google.protobuf.ByteString.EMPTY) {
          setData(other.getData());
        }
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        IopCan.CanCryptoKey parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (IopCan.CanCryptoKey) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int type_ = 0;
      /**
       * <pre>
       * Type of the key.
       * </pre>
       *
       * <code>optional .CanCryptoKey.KeyType type = 1;</code>
       */
      public int getTypeValue() {
        return type_;
      }
      /**
       * <pre>
       * Type of the key.
       * </pre>
       *
       * <code>optional .CanCryptoKey.KeyType type = 1;</code>
       */
      public Builder setTypeValue(int value) {
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of the key.
       * </pre>
       *
       * <code>optional .CanCryptoKey.KeyType type = 1;</code>
       */
      public IopCan.CanCryptoKey.KeyType getType() {
        IopCan.CanCryptoKey.KeyType result = IopCan.CanCryptoKey.KeyType.valueOf(type_);
        return result == null ? IopCan.CanCryptoKey.KeyType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Type of the key.
       * </pre>
       *
       * <code>optional .CanCryptoKey.KeyType type = 1;</code>
       */
      public Builder setType(IopCan.CanCryptoKey.KeyType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        type_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Type of the key.
       * </pre>
       *
       * <code>optional .CanCryptoKey.KeyType type = 1;</code>
       */
      public Builder clearType() {
        
        type_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString data_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <pre>
       * Key binary data.
       * </pre>
       *
       * <code>optional bytes data = 2;</code>
       */
      public com.google.protobuf.ByteString getData() {
        return data_;
      }
      /**
       * <pre>
       * Key binary data.
       * </pre>
       *
       * <code>optional bytes data = 2;</code>
       */
      public Builder setData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        data_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Key binary data.
       * </pre>
       *
       * <code>optional bytes data = 2;</code>
       */
      public Builder clearData() {
        
        data_ = getDefaultInstance().getData();
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return this;
      }


      // @@protoc_insertion_point(builder_scope:CanCryptoKey)
    }

    // @@protoc_insertion_point(class_scope:CanCryptoKey)
    private static final IopCan.CanCryptoKey DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new IopCan.CanCryptoKey();
    }

    public static IopCan.CanCryptoKey getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<CanCryptoKey>
        PARSER = new com.google.protobuf.AbstractParser<CanCryptoKey>() {
      public CanCryptoKey parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new CanCryptoKey(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<CanCryptoKey> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<CanCryptoKey> getParserForType() {
      return PARSER;
    }

    public IopCan.CanCryptoKey getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CanIpnsEntry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CanIpnsEntry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_CanCryptoKey_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_CanCryptoKey_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014IopCan.proto\"\254\001\n\014CanIpnsEntry\022\r\n\005value" +
      "\030\001 \001(\014\022\021\n\tsignature\030\002 \001(\014\0220\n\014validityTyp" +
      "e\030\003 \001(\0162\032.CanIpnsEntry.ValidityType\022\020\n\010v" +
      "alidity\030\004 \001(\014\022\020\n\010sequence\030\005 \001(\004\022\013\n\003ttl\030\006" +
      " \001(\004\"\027\n\014ValidityType\022\007\n\003EOL\020\000\"b\n\014CanCryp" +
      "toKey\022#\n\004type\030\001 \001(\0162\025.CanCryptoKey.KeyTy" +
      "pe\022\014\n\004data\030\002 \001(\014\"\037\n\007KeyType\022\007\n\003RSA\020\000\022\013\n\007" +
      "Ed25519\020\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_CanIpnsEntry_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_CanIpnsEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CanIpnsEntry_descriptor,
        new java.lang.String[] { "Value", "Signature", "ValidityType", "Validity", "Sequence", "Ttl", });
    internal_static_CanCryptoKey_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_CanCryptoKey_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_CanCryptoKey_descriptor,
        new java.lang.String[] { "Type", "Data", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
